spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp

server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true

logging:
  level:
    root: info

spring.datasource:
  username: TEAM01
  password: 111111
  driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  url: jdbc:log4jdbc:oracle:thin:@49.50.174.248:1521/xe

# mybatis framework setting
mybatis:
  type-aliases-package: com.kbstar.dto
  mapper-locations: /mybatis/*.xml